export const ERROR_CODES = {
  // Auth
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  USER_UNAUTHORIZED: 'USER_UNAUTHORIZED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // Courses
  COURSE_NOT_FOUND: 'COURSE_NOT_FOUND',
  COURSE_ALREADY_EXISTS: 'COURSE_ALREADY_EXISTS',

  // Enrollments
  ENROLLMENT_NOT_FOUND: 'ENROLLMENT_NOT_FOUND',
  ENROLLMENT_ALREADY_EXISTS: 'ENROLLMENT_ALREADY_EXISTS',
  ENROLLMENT_EXPIRED: 'ENROLLMENT_EXPIRED',

  // Lessons
  LESSON_ACCESS_DENIED: 'LESSON_ACCESS_DENIED',

  // Payments
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_SIGNATURE_INVALID: 'PAYMENT_SIGNATURE_INVALID',
  PAYMENT_ALREADY_PROCESSED: 'PAYMENT_ALREADY_PROCESSED',

  // Quizzes
  QUIZ_MAX_ATTEMPTS_REACHED: 'QUIZ_MAX_ATTEMPTS_REACHED',

  // Assignments
  ASSIGNMENT_DEADLINE_PASSED: 'ASSIGNMENT_DEADLINE_PASSED',
  ASSIGNMENT_ALREADY_SUBMITTED: 'ASSIGNMENT_ALREADY_SUBMITTED',

  // Certificates
  CERTIFICATE_NOT_ELIGIBLE: 'CERTIFICATE_NOT_ELIGIBLE',
  CERTIFICATE_ALREADY_ISSUED: 'CERTIFICATE_ALREADY_ISSUED',

  // Resources
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',

  // Doubts
  DOUBT_ALREADY_RESOLVED: 'DOUBT_ALREADY_RESOLVED',
  DOUBT_ALREADY_CLOSED: 'DOUBT_ALREADY_CLOSED',
  DOUBT_NOT_RESOLVED: 'DOUBT_NOT_RESOLVED',
  FACULTY_NOT_ASSIGNED: 'FACULTY_NOT_ASSIGNED',
  FACULTY_ALREADY_EXISTS: 'FACULTY_ALREADY_EXISTS',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Server
  SERVER_ERROR: 'SERVER_ERROR',
};

export default ERROR_CODES;