export const ROLES = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  COORDINATOR: 'coordinator',
  HOD: 'hod',
  DEPARTMENT_HEAD: 'department_head',
  FACULTY: 'faculty',
  STUDENT: 'student',
  CONTENT_MANAGER: 'content_manager',
  TEAM_MEMBER: 'team_member',
  MEMBER: 'member',
  STAFF: 'staff',
  INTERN: 'intern',
  VOLUNTEER: 'volunteer',
  CONTENT_EDITOR: 'content_editor',
  VIEWER: 'viewer',
};

export const ROLE_HIERARCHY = [
  ROLES.SUPER_ADMIN,
  ROLES.ADMIN,
  ROLES.COORDINATOR,
  ROLES.HOD,
  ROLES.DEPARTMENT_HEAD,
  ROLES.FACULTY,
  ROLES.CONTENT_MANAGER,
  ROLES.STUDENT,
  ROLES.TEAM_MEMBER,
  ROLES.MEMBER,
  ROLES.STAFF,
  ROLES.INTERN,
  ROLES.VOLUNTEER,
  ROLES.CONTENT_EDITOR,
  ROLES.VIEWER,
];

export const LEARNING_PORTAL_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.ADMIN,
  ROLES.FACULTY,
  ROLES.STUDENT,
  ROLES.CONTENT_MANAGER,
];